version: '3.7'
services:
  redis:
    image: redis
    ports:
      - 6379:6379

  rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgres/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432

volumes:
  postgres-data:
